### PR TITLE
JSON array as a valid first input not only object.

### PR DESCRIPTION
**Pull request by w-vi**
Allow to parse JSON which starts with an array that is, first character in JSON data is '['.

*Example* :
`[80, 443, {x: 25} ]`
Access the 'x' value using path `[2].x`

### CODE REVIEW

**Comment by w-vi** [comment]
I see failing checks but there is no travis file? Are you thinking about setting up a CI?

**Comment by w-vi** [comment]
Just pinging... are you interested in merging it or should I rather keep my fork?

**Comment by cpq** [comment]
I'd be happy to integrate it. Are you fine releasing this patch under the existing Frozen license terms?

**Comment by w-vi** [comment]
Yes absolutely.

**Pull request merged**
